BATCH_LOG_PATH="hdfs://localhost:54310/bgl/BGL.log"
KAFKA_SERVER="localhost:9092"
KAFKA_TOPIC="test"
MONGO_SERVER="mongodb://192.168.86.1:27017/"
MONGO_BATCH_URI=MONGO_SERVER + "bgl_logs.batch_layer"
MONGO_SPEED_URI=MONGO_SERVER + "bgl_logs.speed_layer"
